baseURL = "http://example.org/"
languageCode = "en-us"
title = "Home"
theme = "temple"

[author]
  name = "Arron McCrory"
  github = "arron21"
  email = "arronmccrory@email.com"
  medium = "@arronmccrory"
